export interface Place {
  name: string;
  imageUrl: string;
}

export const places: Place[] = [

  //Oceania
  { name: 'Sydney Opera', imageUrl: '../../../assets/images/operaSidney.jpg' },
  { name: 'Everest', imageUrl: '../../../assets/images/everest.jpg' },
  { name: 'Great Barrier Reef', imageUrl: '../../../assets/images/granBarreraCoral.jpg' },
  { name: 'Mount Cook', imageUrl: '../../../assets/images/mountCook.jpg' },
  { name: 'Sydney', imageUrl: '../../../assets/images/sidney.jpg' },
  { name: 'Bora Bora', imageUrl: '../../../assets/images/boraBora.jpg' },
  { name: 'Milford Sound fiords', imageUrl: '../../../assets/images/pnFiordland.jpg' },
  { name: 'Whitehaven beach', imageUrl: '../../../assets/images/whitehavenBeach.jpg' },
  // { name: 'Rangitoto Island', imageUrl: '../../../assets/images/rangitotoIsland.jpg' },
  { name: 'Uluru mount', imageUrl: '../../../assets/images/uluruMount.jpg' },
  { name: 'St Patrick Cathedral', imageUrl: '../../../assets/images/stPatrickCathedral.jpg' },
  { name: 'Tekapo lake', imageUrl: '../../../assets/images/tekapoLake.jpg' },
  // { name: 'Cable Beach', imageUrl: '../../../assets/images/cableBeach.jpg' },
  { name: 'Wineglass bay', imageUrl: '../../../assets/images/wineglassBay.jpg' },
  { name: 'Cook islands', imageUrl: '../../../assets/images/cookIslands.png' },
  { name: 'Ha Long bay', imageUrl: '../../../assets/images/haLongBay.webp' },
  { name: 'Kakadu National Park', imageUrl: '../../../assets/images/pnKakadu.jpg' },
  { name: 'Fraser island', imageUrl: '../../../assets/images/fraserIsland.jpg' },
  // { name: 'Christchurch cathedral', imageUrl: '../../../assets/images/ChristChurchCathedral.jpg' },
  { name: 'Lord Howe island', imageUrl: '../../../assets/images/lordHoweIsland.jpeg' },
  { name: 'Wanaka lake', imageUrl: '../../../assets/images/wanakaLake.jpg' },
  { name: 'Moorea island', imageUrl: '../../../assets/images/mooreaIsland.jpg' },
  { name: 'St Mary cathedral', imageUrl: '../../../assets/images/stMaryCathedral.jpg' },
  { name: 'Norfolk island', imageUrl: '../../../assets/images/islaNorfolk.jpg' },
  { name: 'Darvaza crater', imageUrl: '../../../assets/images/darvazaCrater.jpg' },
  { name: 'Tetiaroa island', imageUrl: '../../../assets/images/tetiaroaIsland.jpg' },
  { name: 'Taranaki mount', imageUrl: '../../../assets/images/taranakiMount.jpg' },
  { name: 'Taupo lake', imageUrl: '../../../assets/images/taupoLake.jpg' },
  { name: 'Tongariro National Park', imageUrl: '../../../assets/images/pnTongariro.jpg' },

  //Europe
  { name: 'Sagrada Familia', imageUrl: '../../../assets/images/sagradaFamilia.jpg' },
  { name: 'Alhambra', imageUrl: '../../../assets/images/alhambra.jpg' },
  { name: 'Ordesa Valley', imageUrl: '../../../assets/images/ordesaValley.jpg' },
  { name: 'Mosque of Cordoba', imageUrl: '../../../assets/images/mosqueCordoba.jpg' },
  { name: "Dunes of Maspalomas", imageUrl: "../../../assets/images/maspalomasDunes.webp" },
  { name: 'Spain Square of Seville', imageUrl: '../../../assets/images/spainSquare.avif' },
  { name: 'Barcelona', imageUrl: '../../../assets/images/barcelona.jpg' },
  { name: 'Retiro Park', imageUrl: '../../../assets/images/retiroPark.jpg' },
  { name: 'La Rambla of Barcelona', imageUrl: '../../../assets/images/laRambla.avif' },
  { name: 'Montjuïc', imageUrl: '../../../assets/images/montjuic.jpeg' },
  { name: 'Toledo', imageUrl: '../../../assets/images/toledo.jpg' },
  { name: 'Ibiza', imageUrl: '../../../assets/images/ibiza.jpg' },
  { name: 'Great Wall of Ávila', imageUrl: '../../../assets/images/greatWallAvila.webp' },
  { name: 'City of Arts and Sciences museum', imageUrl: '../../../assets/images/cityArtsSciences.jpg' },
  { name: 'Fortress of Segovia', imageUrl: '../../../assets/images/fortressSegovia.jpg' },
  { name: 'Madrid', imageUrl: '../../../assets/images/madrid.jpg' },
  { name: 'Santiago de Compostela', imageUrl: '../../../assets/images/santiagoDeCompostelaCathedral.jpg' },
  { name: 'Montserrat', imageUrl: '../../../assets/images/monasteryMontserrat.jpg' },
  { name: 'Prado Museum', imageUrl: '../../../assets/images/pradoMuseum.avif' },
  { name: 'Guggenheim Museum', imageUrl: '../../../assets/images/guggenheim.jpg' },
  { name: 'Tibidabo', imageUrl: '../../../assets/images/tibidabo.jpg' },
  { name: 'Teide', imageUrl: '../../../assets/images/teide1.jpg' },
  { name: 'Aqueduct of Segovia', imageUrl: '../../../assets/images/segoviaAqueduct.webp' },
  { name: 'Ronda Bridge', imageUrl: '../../../assets/images/rondaBridge.jpg' },
  { name: 'La Concha Beach', imageUrl: '../../../assets/images/laConchaBeach.jpg' },
  { name: 'Great Mosque of Seville', imageUrl: '../../../assets/images/giralda.jpg' },
  { name: 'Main Square of Madrid', imageUrl: '../../../assets/images/mainSquareMadrid.jpg' },
  { name: 'Besalu', imageUrl: '../../../assets/images/besalu.jpg' },
  { name: 'Spain square of Barcelona', imageUrl: '../../../assets/images/spainSquareBarcelona.jpg' },
  { name: 'The Marrows of León', imageUrl: '../../../assets/images/marrows.jpg' },
  { name: 'Batlló House', imageUrl: '../../../assets/images/batlloHouse.webp' },
  { name: 'Gaztelugatxe Monastery', imageUrl: '../../../assets/images/gaztelugatxe.jpg' },
  { name: 'Crater of Sete Cidades', imageUrl: '../../../assets/images/craterSeteCidades.jpg' },
  { name: 'Praça do Comércio', imageUrl: '../../../assets/images/praçaDoComeercio.webp' },
  { name: 'Belém tower', imageUrl: '../../../assets/images/torreDeBelem.jpg' },
  { name: 'Széchenyi baths', imageUrl: '../../../assets/images/széchenyi.jpg' },
  { name: 'The Church of the Savior on Spilled Blood', imageUrl: '../../../assets/images/saviorSpilledBlood.JPG' },
  { name: 'Malbork Castle', imageUrl: '../../../assets/images/malborkCastle.jpg' },
  { name: 'Saint Chapel of Prague', imageUrl: '../../../assets/images/stChapelPrague.jpg' },
  { name: 'Palais des Papes', imageUrl: '../../../assets/images/palaisDesPapes.jpg' },
  { name: 'Windsor Castle', imageUrl: '../../../assets/images/windsorCastle.jpg' },
  { name: 'Rialto Bridge', imageUrl: '../../../assets/images/rialtoBridge.jpg' },
  { name: 'Riga', imageUrl: '../../../assets/images/riga.jpg' },
  { name: 'Puerta de Alcalá', imageUrl: '../../../assets/images/puertaAlcala.jpg' },
  { name: 'Wawel Castle', imageUrl: '../../../assets/images/wawelCastle.jpg' },
  { name: 'Dubrovnik', imageUrl: '../../../assets/images/dubrovnik.jpg' },
  { name: 'St. Michael and St. Gudula Cathedral', imageUrl: '../../../assets/images/StMichaelStGudulaCathedral.jpg' },
  { name: 'Chambord Castle', imageUrl: '../../../assets/images/chambordCastle.jpg' },
  { name: 'European Parliament', imageUrl: '../../../assets/images/euroParlament.jpg' },
  // { name: 'Liberty Bridge', imageUrl: '../../../assets/images/libertyBridge.jpg' },
  { name: 'Chain Bridge', imageUrl: '../../../assets/images/chainBridge.jpg' },
  { name: 'Bran Castle', imageUrl: '../../../assets/images/branCastle.jpg' },
  { name: 'Tower Bridge', imageUrl: '../../../assets/images/towerBridge.jpg' },
  { name: 'Schönbrunn Palace', imageUrl: '../../../assets/images/schönbrunnPalace.avif' },
  { name: 'Hungarian Parliament', imageUrl: '../../../assets/images/hungarianParliament.jpg' },
  { name: 'Diocletian Palace', imageUrl: '../../../assets/images/diocletianPalace.webp' },
  { name: 'Edinburgh Castle', imageUrl: '../../../assets/images/edinburghCastle.jpg' },
  { name: 'Vila Franca do Campo Island', imageUrl: '../../../assets/images/vilaFrancaCampoIsland.jpg' },
  { name: 'Benagil', imageUrl: '../../../assets/images/benagil.jpg' },
  { name: 'Cape Sao Vicente', imageUrl: '../../../assets/images/caboSanVicente.jpg' },
  { name: 'Big Ben', imageUrl: '../../../assets/images/bigBen.jpg' },
  { name: 'Zermatt', imageUrl: '../../../assets/images/zermatt.jpg' },
  { name: 'Lucerne', imageUrl: '../../../assets/images/lucerne.jpg' },
  { name: 'Interlaken', imageUrl: '../../../assets/images/interlaken.jpg' },
  { name: 'Geneva', imageUrl: '../../../assets/images/geneva.jpg' },
  { name: 'Lauterbrunnen', imageUrl: '../../../assets/images/lauterbrunnen.jpg' },
  { name: 'Schilthorn', imageUrl: '../../../assets/images/schilthorn.jpeg' },
  { name: 'St Stephan Cathedral', imageUrl: '../../../assets/images/stStephansCathedral.jpg' },
  { name: 'Zurich', imageUrl: '../../../assets/images/zurich.jpg' },
  { name: 'Carcassonne', imageUrl: '../../../assets/images/carcassonne.jpg' },
  { name: 'Bruges', imageUrl: '../../../assets/images/bruges.jpg' },
  { name: 'Reykjavik', imageUrl: '../../../assets/images/reykjavik.jpg' },
  { name: 'Vatican', imageUrl: '../../../assets/images/vatican.jpg' },
  { name: 'Praga Castle', imageUrl: '../../../assets/images/pragaCastle.jpg' },
  { name: 'Duomo of Florence', imageUrl: '../../../assets/images/duomoFlorence.jpg' },
  { name: 'St. Marco Square', imageUrl: '../../../assets/images/stMarcoSquare.jpg' },
  { name: 'Giants Causeway', imageUrl: '../../../assets/images/giantsCauseway.jpg' },
  { name: 'Palace of Versailles', imageUrl: '../../../assets/images/palaceVersailles.jpg' },
  { name: 'Paris Opera', imageUrl: '../../../assets/images/operaParis.jpg' },
  { name: 'Eiffel tower', imageUrl: '../../../assets/images/eiffel.jpg' },
  { name: 'Lourdes Sanctuary', imageUrl: '../../../assets/images/lourdesSanctuary.avif' },
  { name: "Louvre Museum", imageUrl: "../../../assets/images/louvreMuseum.jpg" },
  { name: "Mont Saint-Michel", imageUrl: "../../../assets/images/montSaintMichel.jpg" },
  { name: 'Chartres cathedral', imageUrl: '../../../assets/images/chartresCathedral.webp' },
  { name: 'Notre-Dame', imageUrl: '../../../assets/images/notreDame.jpg' },
  { name: 'The Colosseum', imageUrl: '../../../assets/images/coliseo.jpg' },
  { name: 'Pisa tower', imageUrl: '../../../assets/images/torrePisa.jpg' },
  { name: 'The Sistine Chapel', imageUrl: '../../../assets/images/cSixtina.jpg' },
  { name: 'St. Peter Basilica', imageUrl: '../../../assets/images/sanPedroBasilica.avif' },
  { name: 'Florence', imageUrl: '../../../assets/images/florencia.jpeg' },
  { name: 'Trevi Fountain', imageUrl: '../../../assets/images/treviFountain.jpg' },
  { name: 'The Acropolis of Athens', imageUrl: '../../../assets/images/acropolisAtenas.jpg' },
  { name: 'Parthenon', imageUrl: '../../../assets/images/parthenon.jpg' },
  { name: 'Zeus temple', imageUrl: '../../../assets/images/ZeusTemple.jpg' },
  { name: 'Santorini', imageUrl: '../../../assets/images/santorini.jpg' },
  { name: "Pantheon of Agripa", imageUrl: "../../../assets/images/agripaPantheon.jpg" },
  // { name: 'Delphi Sanctuary', imageUrl: '../../../assets/images/.jpg' },
  { name: 'Neuschwanstein Castle', imageUrl: '../../../assets/images/neuschwanstein.jpg' },
  { name: "Brandenburg Gate", imageUrl: "../../../assets/images/brandenburgGate.jpg" },
  { name: 'Berlin', imageUrl: '../../../assets/images/berlin.jpg' },
  { name: 'Buckingham Palace', imageUrl: '../../../assets/images/buckingham.jpg' },
  { name: 'London', imageUrl: '../../../assets/images/londres.jpg' },
  { name: 'London tower', imageUrl: '../../../assets/images/towerLondon.jpg' },
  { name: 'St Paul Cathedral', imageUrl: '../../../assets/images/stPaulCathedral.jpg' },
  { name: "Stonehenge", imageUrl: "../../../assets/images/stonehenge.jpg" },
  { name: 'Charles Bridge', imageUrl: '../../../assets/images/charlesBridge.jpg' },
  { name: 'Sintra palace', imageUrl: '../../../assets/images/sintraPalace.webp' },
  { name: 'Mafra Palace', imageUrl: '../../../assets/images/mafraPalace.jpg' },
  { name: 'Sanctuary of Fátima', imageUrl: '../../../assets/images/fatimaSanctuary.jpg' },
  { name: 'Lisboa', imageUrl: '../../../assets/images/lisboa.jpg' },
  { name: 'Norwegian fjords', imageUrl: '../../../assets/images/norwegianFiords.jpg' },
  // { name: 'Keukenhof garden', imageUrl: '../../../assets/images/keukenhofGarden.jpg' },
  { name: 'Amsterdam', imageUrl: '../../../assets/images/amsterdam.jpg' },
  { name: 'Vienna', imageUrl: '../../../assets/images/vienna.webp' },
  { name: 'Viena Opera', imageUrl: '../../../assets/images/operaViena.jpg' },
  { name: 'Salzburg', imageUrl: '../../../assets/images/salzburg.jpg' },
  { name: 'Hallstatt', imageUrl: '../../../assets/images/hallstatt.jpg' },
  { name: 'Plitvice National Park', imageUrl: '../../../assets/images/pnPlitvice.jpg' },
  { name: 'Stockholm', imageUrl: '../../../assets/images/stockholm.jpg' },
  { name: 'Praga', imageUrl: '../../../assets/images/praga.jpg' },
  { name: 'Moher cliffs', imageUrl: '../../../assets/images/moherCliff.jpg' },
  { name: 'The Blue Mosque', imageUrl: '../../../assets/images/blueMosque.jpg' },

  //Africa
  { name: 'Pyramids of Giza', imageUrl: '../../../assets/images/piramidesGiza.jpg' },
  { name: "Luxor temple", imageUrl: "../../../assets/images/luxorTemple.jpeg" },
  { name: "Abu Simbel", imageUrl: "../../../assets/images/abuSimbel.jpg" },
  { name: 'Karnak temple', imageUrl: '../../../assets/images/karnakTemple.jpg' },
  { name: 'Cairo', imageUrl: '../../../assets/images/cairo.jpg' },
  { name: 'Okavango delta', imageUrl: '../../../assets/images/okavangoDelta.jpg' },
  { name: 'Mauritius island', imageUrl: '../../../assets/images/mauritiusIsland.jpeg' },
  { name: 'Casablanca', imageUrl: '../../../assets/images/casablanca.jpg' },
  { name: 'Ait Ben Haddou', imageUrl: '../../../assets/images/aitBenHaddou.jpg' },
  { name: 'Timbuktu', imageUrl: '../../../assets/images/timbuktu.jpg' },
  { name: 'Fez', imageUrl: '../../../assets/images/fez.jpg' },
  { name: 'Sahara desert', imageUrl: '../../../assets/images/saharaDesert.avif' },
  { name: 'Mosque of Hassan II', imageUrl: '../../../assets/images/mosqueHassanII.jpeg' },
  { name: 'Marrakech', imageUrl: '../../../assets/images/marrakech.jpg' },
  { name: 'Majorelle garden', imageUrl: '../../../assets/images/majorelleGarden.jpg' },
  { name: 'Jemaa El Fna Square', imageUrl: '../../../assets/images/jemaaElFnaSquare.jpg' },
  { name: 'Koutoubia', imageUrl: '../../../assets/images/koutoubia.jpg' },
  // { name: '', imageUrl: '../../../assets/images/.jpg' },
  // { name: '', imageUrl: '../../../assets/images/.jpg' },
  // { name: '', imageUrl: '../../../assets/images/.jpg' },
  // { name: '', imageUrl: '../../../assets/images/.jpg' },
  // { name: '', imageUrl: '../../../assets/images/.jpg' },
  { name: 'Kilimanjaro', imageUrl: '../../../assets/images/kilimanjaro.jpg' },
  { name: 'Serengeti National Park', imageUrl: '../../../assets/images/pnSerengeti.jpg' },
  { name: 'Mara river', imageUrl: '../../../assets/images/maraRiver.jpg' },
  { name: "Table mountain", imageUrl: "../../../assets/images/tableMountain.webp" },
  { name: "Kruger National Park", imageUrl: "../../../assets/images/pnKruger.webp" },
  { name: 'Victoria Falls', imageUrl: '../../../assets/images/victoriaFalls.jpg' },

  //Asia
  { name: 'Saint Basil Cathedral', imageUrl: '../../../assets/images/cathedralSanBasilio.jpg' },
  { name: "Red Square", imageUrl: "../../../assets/images/redSquare.jpg" },
  { name: 'Kremlin', imageUrl: '../../../assets/images/kremlin.jpg' },
  { name: 'Motherland statue', imageUrl: '../../../assets/images/motherlandStatue.jpg' },
  { name: 'St. Petersburg', imageUrl: '../../../assets/images/stPetersburg.jpg' },

  { name: 'Great Wall China', imageUrl: '../../../assets/images/granMurallaChina.jpg' },
  { name: 'Taj Mahal', imageUrl: '../../../assets/images/tajMahal.jpg' },
  { name: 'Forbidden City', imageUrl: '../../../assets/images/ciudadProhibida.jpg' },
  { name: 'Beijing', imageUrl: '../../../assets/images/beijing.jpeg' },
  { name: 'Angkor Wat temple', imageUrl: '../../../assets/images/angkorWat.jpg' },
  { name: 'Monte Fuji', imageUrl: '../../../assets/images/monteFuji.jpg' },
  { name: 'Petra', imageUrl: '../../../assets/images/petra.jpg' },
  { name: 'Tokyo temple', imageUrl: '../../../assets/images/tokyoTower.jpg' },
  { name: 'Borobudur temple', imageUrl: '../../../assets/images/borobudurTemple.jpg' },
  { name: 'Hatshepsut temple', imageUrl: '../../../assets/images/hatshepsutTemple.jpg' },
  { name: 'Potala palace', imageUrl: '../../../assets/images/potalaPalace.jpg' },
  { name: 'Jerusalem', imageUrl: '../../../assets/images/jerusalem.jpeg' },
  { name: 'Buddha of Leshan', imageUrl: '../../../assets/images/leshanBuddha.jpg' },
  { name: 'Topkapi palace', imageUrl: '../../../assets/images/topkapiPalace.jpg' },
  { name: "Meenakshi temple", imageUrl: "../../../assets/images/meenakshiTemple.jpg" },
  { name: "Tirta Empul temple", imageUrl: "../../../assets/images/tirtaEmpulTemple.jpg" },
  { name: "Wat Rong Khun temple", imageUrl: "../../../assets/images/watRongKhunTemple.jpg" },
  { name: "Wat Saket temple",imageUrl: "../../../assets/images/watSaketTemple.jpg" },
  { name: "Wat Benchamabophit temple", imageUrl: "../../../assets/images/watBenchamabophitTemple.jpg" },
  { name: "Ta Prohm temple", imageUrl: "../../../assets/images/taProhmTemple.jpg" },
  { name: "Wat Suan Dok temple", imageUrl: "../../../assets/images/watSuanDokTemple.jpg" },
  { name: "Kuala Lumpur tower", imageUrl: '../../../assets/images/kualaLumpurTower.jpg' },
  { name: 'Golden Rock temple', imageUrl: '../../../assets/images/goldenRockTemple.jpg' },
  { name: 'Shanghai', imageUrl: '../../../assets/images/shanghai.jpg' },
  { name: 'Himeji castle', imageUrl: '../../../assets/images/himejiCastle.png' },
  { name: 'Aoraki National Park', imageUrl: '../../../assets/images/pnAoraki.jpg' },
  { name: 'Bangkok Palace', imageUrl: '../../../assets/images/bangkokPalace.jpg' },
  { name: 'Maldivas Islands', imageUrl: '../../../assets/images/maldivasIslands.webp' },
  { name: 'Angkor Thom temple', imageUrl: '../../../assets/images/angkorThomTemple.jpg' },
  { name: 'Istanbul', imageUrl: '../../../assets/images/istanbul.jpg' },
  { name: 'Zhangjiajie', imageUrl: '../../../assets/images/zhangjiajie.jpg' },
  { name: 'Uluwatu temple', imageUrl: '../../../assets/images/uluwatuTemple.jpg' },
  { name: 'Fushimi Inari Taisha', imageUrl: '../../../assets/images/fushimiInariTaisha.jpg' },
  { name: 'Bagan', imageUrl: '../../../assets/images/bagan.jpg' },
  { name: 'Kinkakuji', imageUrl: '../../../assets/images/kinkakuji.jpg' },
  { name: 'Meiji Jingu temple', imageUrl: '../../../assets/images/meijiJinguTemple.jpg' },
  { name: 'Phi Phi', imageUrl: '../../../assets/images/phiPhi.jpg' },
  { name: 'Prambanan temple', imageUrl: '../../../assets/images/prambananTemple.jpg' },
  { name: 'Bali', imageUrl: '../../../assets/images/bali.jpg' },
  { name: 'Kyoto', imageUrl: '../../../assets/images/kyoto.jpg' },
  { name: 'Rock Temple', imageUrl: '../../../assets/images/rockTemple.jpg' },
  { name: 'Kiyomizu-dera temple', imageUrl: '../../../assets/images/kiyomizuDeraTemple.jpg' },
  { name: 'Wat Xieng Thong temple', imageUrl: '../../../assets/images/watXiengThongTemple.jpg' },
  { name: 'Pashupatinath temple', imageUrl: '../../../assets/images/pashupatinathTemple.jpg' },
  { name: 'Boudhanath temple', imageUrl: '../../../assets/images/boudhanathTemple.jpg' },
  { name: 'Jokhang temple', imageUrl: '../../../assets/images/jokhangTemple.jpg' },
  { name: 'Wat Chedi Luang temple', imageUrl: '../../../assets/images/watChediLuangTemple.jpg' },
  { name: 'Dubai', imageUrl: '../../../assets/images/duabi.png' },
  { name: 'Sigiriya temple', imageUrl: '../../../assets/images/sigiriyaTemple.jpg' },
  { name: 'Todaiji temple', imageUrl: '../../../assets/images/todaijiTemple.jpg' },
  { name: 'Wat Pho temple', imageUrl: '../../../assets/images/watPhoTemple.jpg' },
  { name: 'Singapur', imageUrl: '../../../assets/images/singapur.jpg' },
  { name: 'Wat Phra Kaew temple', imageUrl: '../../../assets/images/watPhraKaewTemple.jpg' },
  { name: 'Wat Arun temple', imageUrl: '../../../assets/images/watArunTemple.jpg' },
  { name: 'Bangkok', imageUrl: '../../../assets/images/bangkok.png' },
  { name: 'Wat Phra That Doi Suthep', imageUrl: '../../../assets/images/watPhraThatDoiSuthepTemple.jpg' },

  //America
  { name: 'Machu Picchu', imageUrl: '../../../assets/images/machuPicchu.jpg' },
  { name: 'Statue of Liberty', imageUrl: '../../../assets/images/estatuaLibertad.jpg' },
  { name: 'Grand Canyon', imageUrl: '../../../assets/images/granCanon.jpg' },
  { name: 'Yellowstone', imageUrl: '../../../assets/images/yellowstone.jpg' },
  { name: 'Boiler of Yellowstone', imageUrl: '../../../assets/images/calderaYellowstone.jpg' },
  { name: 'Iguazú Falls', imageUrl: '../../../assets/images/iguazu.jpg' },
  { name: 'Niagara Falls', imageUrl: '../../../assets/images/niagara.jpg' },
  { name: 'Cristo Redentor', imageUrl: '../../../assets/images/cristoRedentor.jpg' },
  { name: 'Easter Island', imageUrl: '../../../assets/images/easterIsland.jpg' },
  { name: 'Yosemite', imageUrl: '../../../assets/images/yosemite.jpg' },
  { name: 'Monte Rushmore', imageUrl: '../../../assets/images/rushmore.jpg' },
  { name: 'Banff National Park', imageUrl: '../../../assets/images/pnBanff.jpg' },
  { name: 'Argentine glaciers', imageUrl: '../../../assets/images/argentineGlaciers.jpg' },
  { name: 'Perito Moreno', imageUrl: '../../../assets/images/peritoMoreno.jpg' },
  { name: 'Mauna Loa', imageUrl: '../../../assets/images/maunaLoa.webp' },
  { name: 'Paine towers', imageUrl: '../../../assets/images/paineTowers.jpg' },
  { name: "Chichén Itzá", imageUrl: "../../../assets/images/chichenItza.jpg" },
  // { name: "Temple of Delos", imageUrl: "../../../assets/images/delosTemple.jpg" },
  { name: "CN Tower", imageUrl: "../../../assets/images/cnTower.webp" },
  { name: "History Museum of New York", imageUrl: "../../../assets/images/historyMuseumNY.jpg" },
  { name: "History Museum of London", imageUrl: "../../../assets/images/historyMuseumLondon.jpg" },
  { name: "Smithsonian", imageUrl: "../../../assets/images/smithsonian.jpg" },
  { name: "Christ of concord", imageUrl: "../../../assets/images/christConcord.jpg" },
  // { name: "Asuncion temple", imageUrl: "../../../assets/images/asuncionTemple.jpg" },
  // { name: 'Butchart Gardens', imageUrl: '../../../assets/images/butchartGarden.webp' },
  { name: 'Zion National Park', imageUrl: '../../../assets/images/pnZion.jpg' },
  { name: 'Quebec', imageUrl: '../../../assets/images/quebec.webp' },
  { name: 'Death Valley', imageUrl: '../../../assets/images/deathValley.webp' },
  { name: 'Titicaca Lake', imageUrl: '../../../assets/images/titicacaLake.jpg' },
  { name: 'Angel falls', imageUrl: '../../../assets/images/angelFalls.jpg' },
  { name: 'Everglades National Park', imageUrl: '../../../assets/images/pnEverglades.webp' },
  { name: 'Buenos Aires', imageUrl: '../../../assets/images/buenosAires.jpg' },
  { name: 'Roraima mount', imageUrl: '../../../assets/images/roraimaMount.jpg' },
  { name: 'Arches National Park', imageUrl: '../../../assets/images/pnArches.jpg' },
  { name: 'Rocky Montains', imageUrl: '../../../assets/images/rockyMontains.jpg' },
  { name: 'Río de Janeiro', imageUrl: '../../../assets/images/rioJaneiro.webp' },
  { name: 'San Francisco', imageUrl: '../../../assets/images/sanFrancisco.jpg' },
  { name: 'Manuel Antonio National Park', imageUrl: '../../../assets/images/pnManuelAntonio.jpg' },
  { name: 'Sanctuary of Guadalupe', imageUrl: '../../../assets/images/guadalupeSanctuary.jpg' },
  { name: 'Los Angeles', imageUrl: '../../../assets/images/losAngeles.jpg' },
  { name: 'New Orleans', imageUrl: '../../../assets/images/newOrleans.jpg' },
  { name: 'Montana Glaciers ', imageUrl: '../../../assets/images/montanaGlaciers.jpg' },
  { name: 'Vancouver', imageUrl: '../../../assets/images/vancouver.jpg' },
  { name: 'Galapagos islands', imageUrl: '../../../assets/images/galapagosIslands.jpg' },

  // { name: '', imageUrl: '../../../assets/images/.jpg' },
  // { name: '', imageUrl: '../../../assets/images/.jpg' },
  // { name: '', imageUrl: '../../../assets/images/.jpg' },
  // { name: '', imageUrl: '../../../assets/images/.jpg' },
  // { name: '', imageUrl: '../../../assets/images/.jpg' },
];


/*
templos de israel
cositas de Jordania
golden temple sri lanka
*/

/*
mejorar foto
casa batllo
liberty bridge
*/
