export const gifs = [
  "../../../assets/gifs/1.gif ", "../../../assets/gifs/dog.gif",
  "../../../assets/gifs/llama.gif", "../../../assets/gifs/sad.gif",
  "../../../assets/gifs/tractor.gif", "../../../assets/gifs/giphy (1).gif",
  "../../../assets/gifs/giphy (2).gif", "../../../assets/gifs/giphy (3).gif",
  "../../../assets/gifs/giphy (4).gif", "../../../assets/gifs/giphy (5).gif",
  "../../../assets/gifs/giphy (6).gif", "../../../assets/gifs/giphy (7).gif",
  "../../../assets/gifs/giphy (8).gif", "../../../assets/gifs/giphy (9).gif",
  "../../../assets/gifs/giphy (10).gif", "../../../assets/gifs/giphy (11).gif",
  "../../../assets/gifs/giphy (12).gif", "../../../assets/gifs/giphy (13).gif",
  "../../../assets/gifs/giphy (14).gif", "../../../assets/gifs/giphy (15).gif",
  "../../../assets/gifs/giphy (16).gif", "../../../assets/gifs/giphy (17).gif",
  "../../../assets/gifs/giphy (18).gif", "../../../assets/gifs/giphy (19).gif",
  "../../../assets/gifs/giphy (20).gif", "../../../assets/gifs/giphy (21).gif",
  "../../../assets/gifs/giphy (22).gif", "../../../assets/gifs/giphy (23).gif",
  "../../../assets/gifs/giphy (24).gif", "../../../assets/gifs/giphy (25).gif",
  "../../../assets/gifs/giphy (26).gif", "../../../assets/gifs/giphy (27).gif",
  "../../../assets/gifs/giphy (28).gif", "../../../assets/gifs/giphy (29).gif",
  "../../../assets/gifs/giphy (30).gif", "../../../assets/gifs/giphy (31).gif",
  "../../../assets/gifs/giphy (32).gif", "../../../assets/gifs/giphy (33).gif",
  "../../../assets/gifs/giphy (34).gif", "../../../assets/gifs/giphy (35).gif",
  "../../../assets/gifs/giphy (36).gif", "../../../assets/gifs/giphy (37).gif",
  "../../../assets/gifs/giphy (38).gif", "../../../assets/gifs/sheep.gif",
  // "../../../assets/gifs/giphy ().gif", "../../../assets/gifs/giphy ().gif",
  // "../../../assets/gifs/giphy ().gif", "../../../assets/gifs/giphy ().gif",

];
